# Generated by Django 5.2.6 on 2025-09-26 12:39
import logging

from django.db import migrations


logger = logging.getLogger(__name__)


def setup_default_admin_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    if User.objects.filter(username='admin').exists():
        logger.info('Default admin user already exists')
        return
    
    User.objects.create_superuser(
        username='admin',
        password='admin',
        email='admin@example.com'
    )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(setup_default_admin_user),
    ]
